package:
  name: vlachos-group-mutt
  version: "1.0.0"

source:
  git_rev: "master"
  git_url: "https://github.com/VlachosGroup/PyMUTT.git"

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - ase >=3.16.2
    - matplotlib >=2.2.3
    - numpy >=1.15.1
    - scipy >=1.1.0
    - pandas >=0.20.3

about:
  home: "https://github.com/VlachosGroup/PyMUTT/"
  license: MIT
  license_file: LICENSE.md
